version: "3.9"
services:
  doc88:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'doc88'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  web:
    image: urnau/app1-php:prod-nginx-php-fpm8.2.3
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.3-fpm-bullseye'
    volumes:
      - ./app:/var/www/app
    ports:
      - "80:80" #http
      - "443:443" #https
volumes:
  my-db:
  
